### ISSUE TITLE
Pdfarranger is in the official Fedora repositories

### ISSUE THREAD

**Issue by dreua** [rpmsphere/source#1]
I'm not using rpmsphere myself but I am code contributor and Fedora package maintainer of pdfarranger. I noticed that rpmsphere ships an outdated version of pdfarranger and I wonder if it should be removed from rpmsphere in favour of the version in the official repository.
Thank you for your interest in pdfarranger and let me know if I can help you with anything related to this issue!

**Comment by dreua** [comment]
Links to the files:
- https://github.com/rpmsphere/source/blob/master/p/pdfarranger-1.1-1.src.rpm
- https://github.com/rpmsphere/noarch/blob/master/p/pdfarranger-1.1-1.noarch.rpm

I was thinking about sending your pull requests to update the packages to the latest versions but I guess with the repodata that would be rather complicated, right?

**Comment by bluebat** [comment]
Thanks for informing this. Files have been removed to avoid conflict with the official repository.
