### ISSUE TITLE
ccextractor is built with ocr enabled but without hardsubx support

### ISSUE THREAD

**Issue by ohsix** [rpmsphere/source#1]
for some reason these are separate options, but without hardsubx ccextractor isn't actually able to ocr many file formats

https://github.com/CCExtractor/ccextractor/blob/8a81a57a24324ea731e08d9e0392cd8490f43723/linux/Makefile.am#L341

going by BuildRequires it looks like it may have worked in the past, but now it needs --enable-hardsubx

**Comment by bluebat** [comment]
Updated.
