### ISSUE TITLE
kazam update

### ISSUE THREAD

**Issue by sergiomb2** [rpmsphere/source#10]
I like the result see all sources in https://copr-dist-git.fedorainfracloud.org/cgit/sergiomb/clonezilla/kazam.git/tree/ I updated to 1.5.7 with same ideas of mageia package ... but be carefull avoid patch 0001-Port-to-Ayatana-AppIndicator.patch , Ayatana appIndicator does not exist in Fedora and conflicts with the original appIndicator

**Comment by bluebat** [comment]
done.
