### ISSUE TITLE
Lapce out of date and other issues

### ISSUE THREAD

**Issue by Titaniumtown** [rpmsphere/source#3]
Lapce version 0.1.3 has been released, and I noticed that the spec file is using `--release`, lapce has a profile meant for releases that is preferred: `--profile release-lto` which should be changed

**Comment by bluebat** [comment]
updated to 0.1.3 but still using `--release` because failed to build with `--profile release-lto`

**Comment by sergiomb2** [comment]
BTW I wonder where I should write, or is the best place to write to you   ? 

Anyway , I build clonezilla and mbr on copr [1], after use successfully clonezilla. I invite you to build all packages that not requires RPMfusion and are allowed on Fedora [2] on copr, is a very good place .

Thank you for your packages 

[1]
https://copr.fedorainfracloud.org/coprs/sergiomb/clonezilla/
Description

clonezilla from RPMSpehre

[2]
https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr

**Comment by bluebat** [comment]
It's "RPMSphere", not "RPMSpehre" :)
Feel free to promote them in any form.
