### ISSUE TITLE
trimage needs wrong python version on fedora 37

### ISSUE THREAD

**Issue by elwerene** [rpmsphere/source#4]
Error: 
 Problem: problem with installed package trimage-1.0.6-2.noarch
  - package trimage-1.0.6-2.noarch requires python(abi) = 3.10, but none of the providers can be installed
  - python3-3.10.8-1.fc36.x86_64 does not belong to a distupgrade repository
  
Fedora 37 provides python(abi) = 3.11

**Comment by elwerene** [comment]
oh wait, fedora 37 will only be released tomorrow^^

**Comment by bluebat** [comment]
Currently I have no resource to rebuild the repository on Fedora 37.
You may try to rebuild it by:
rpmbuild --rebuild https://github.com/rpmsphere/source/raw/master/t/trimage-1.0.6-2.src.rpm

**Comment by elwerene** [comment]
That worked!

**Comment by bluebat** [comment]
You have good luck! rpmsphere/noarch#3 may be more difficult...
Thanks for your offer. Actually I should rebuild all the 2800+ packages in https://github.com/rpmsphere/source :)
