### ISSUE TITLE
newer version of Textadept (and modules)

### ISSUE THREAD

**Issue by ousia** [rpmsphere/source#5]
@bluebat,

would you be so kind to release a new srpm for Textadept-11.4 and for its modules (https://github.com/orbitalquark/textadept/releases/tag/latest)?

Many thanks for your help.

**Comment by bluebat** [comment]
updated:
https://github.com/rpmsphere/source/raw/master/t/textadept-11.4-1.src.rpm
https://github.com/rpmsphere/x86_64/raw/master/t/textadept-11.4-1.x86_64.rpm
