### ISSUE TITLE
Textadept 12 and modules

### ISSUE THREAD

**Issue by ousia** [rpmsphere/source#8]
@bluebat,

Textadept 12 (and the modules) have been released ten days ago (https://github.com/orbitalquark/textadept/releases/latest).

It would be great it you could add them to RPM Sphere.

Many thanks for your help.

**Comment by bluebat** [comment]
updated to 12.1
textadept-modules maybe sometime :)

**Comment by bluebat** [comment]
You are welcome.
Feel free to open an issue.
