### ISSUE TITLE
please subscribe to Textadept releases

### ISSUE THREAD

**Issue by ousia** [rpmsphere/source#9]
@bluebat,

this comes from https://github.com/rpmsphere/source/issues/8#issuecomment-1729817036 (my request) and https://github.com/rpmsphere/source/issues/8#issuecomment-1730586195 (your reply):

Would you be so kind to consider subscribing to releases and security alerts in [Textadept] (https://github.com/orbitalquark/textadept) (as custom notifications), so that new versions come directly to your inbox?

I mean, this is to avoid having a new issue when a new version has been released.

Many thanks for your help again.

**Comment by bluebat** [comment]
No, thanks.
I meant, please open a new issue when a new version has been released.
